-- ============================================================================
-- MULTILINGUAL MORPHEME/CONCEPT VOCABULARY SCHEMA
-- Secondary tables that reference the core morphemes table
-- Generated by planner - review and refine
-- ============================================================================

PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;

-- ============================================================================
-- 1. LANGUAGE HIERARCHY
-- ============================================================================
-- Levels: family → branch → group → language → dialect → register

CREATE TABLE language_families (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,

    -- Hierarchy
    parent_id INTEGER,
    level TEXT NOT NULL CHECK (level IN (
        'family', 'branch', 'group', 'language', 'dialect', 'register'
    )),

    -- Standard codes
    iso_639_3 TEXT,
    iso_639_1 TEXT,
    glottolog_code TEXT,
    wals_code TEXT,
    bcp47_tag TEXT,

    -- Typological defaults (inherited down tree)
    default_word_order TEXT,
    default_head_direction TEXT,
    default_case_system TEXT,
    default_morphology_type TEXT,
    default_script TEXT,

    -- Inheritance control
    inherits_grammar INTEGER DEFAULT 1,
    grammar_override TEXT,

    -- NLP tool availability
    spacy_model TEXT,
    stanza_model TEXT,
    fasttext_supported INTEGER DEFAULT 0,
    unimorph_available INTEGER DEFAULT 0,

    -- Confidence/provenance
    confidence REAL DEFAULT 0.5,
    source TEXT,

    -- Metadata
    speaker_count INTEGER,
    endangered_status TEXT,
    notes TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT,

    FOREIGN KEY (parent_id) REFERENCES language_families(id),
    UNIQUE (name, parent_id)
);

-- ============================================================================
-- 2. MORPHEME CATEGORIES
-- ============================================================================

CREATE TABLE morpheme_categories (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    parent_id INTEGER,
    description TEXT,
    sort_order INTEGER DEFAULT 0,

    FOREIGN KEY (parent_id) REFERENCES morpheme_categories(id)
);

-- ============================================================================
-- 3. MORPHEME METADATA (extends fixed morphemes table)
-- ============================================================================

CREATE TABLE morpheme_metadata (
    morpheme_id INTEGER PRIMARY KEY,

    category_id INTEGER,
    subcategory TEXT,
    semantic_domain TEXT,
    composable INTEGER DEFAULT 1,
    productivity REAL DEFAULT 0.5,
    core_level INTEGER DEFAULT 0,

    is_modifier INTEGER DEFAULT 0,
    is_bound INTEGER DEFAULT 0,
    is_derivational INTEGER DEFAULT 0,
    is_inflectional INTEGER DEFAULT 0,

    confidence REAL DEFAULT 0.8,
    source TEXT DEFAULT 'manual',
    verified INTEGER DEFAULT 0,

    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT,

    FOREIGN KEY (morpheme_id) REFERENCES morphemes(id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES morpheme_categories(id)
);

-- ============================================================================
-- 4. SURFACE FORMS (CRITICAL FOR TOKENIZATION)
-- ============================================================================

CREATE TABLE surface_forms (
    id INTEGER PRIMARY KEY,

    morpheme_id INTEGER NOT NULL,
    language_id INTEGER NOT NULL,

    surface_form TEXT NOT NULL,
    normalized_form TEXT,
    phonetic_form TEXT,

    morpheme_type TEXT DEFAULT 'word' CHECK (morpheme_type IN (
        'root', 'stem', 'prefix', 'suffix', 'infix', 'circumfix',
        'word', 'clitic', 'particle', 'phrase'
    )),

    pos_tag TEXT,
    pos_features TEXT,

    frequency INTEGER DEFAULT 0,
    register TEXT,

    sense_id INTEGER DEFAULT 0,
    gloss TEXT,
    usage_example TEXT,

    derived_from_id INTEGER,
    etymology_type TEXT,
    proto_form TEXT,

    confidence REAL DEFAULT 0.8,
    source TEXT DEFAULT 'wiktionary',
    source_id TEXT,

    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT,

    FOREIGN KEY (morpheme_id) REFERENCES morphemes(id) ON DELETE CASCADE,
    FOREIGN KEY (language_id) REFERENCES language_families(id),
    FOREIGN KEY (derived_from_id) REFERENCES surface_forms(id),

    UNIQUE (language_id, surface_form, pos_tag, sense_id)
);

-- ============================================================================
-- 5. ALLOMORPHS
-- ============================================================================

CREATE TABLE allomorphs (
    id INTEGER PRIMARY KEY,

    surface_form_id INTEGER NOT NULL,
    variant_form TEXT NOT NULL,

    condition_type TEXT NOT NULL CHECK (condition_type IN (
        'phonological', 'morphological', 'lexical', 'free_variation'
    )),
    condition_pattern TEXT,

    example_word TEXT,
    example_context TEXT,
    frequency INTEGER DEFAULT 0,
    notes TEXT,

    FOREIGN KEY (surface_form_id) REFERENCES surface_forms(id) ON DELETE CASCADE,
    UNIQUE (surface_form_id, variant_form)
);

-- ============================================================================
-- 6. ETYMOLOGY LINKS
-- ============================================================================

CREATE TABLE etymology_links (
    id INTEGER PRIMARY KEY,

    source_form_id INTEGER,
    source_lang TEXT NOT NULL,
    source_term TEXT NOT NULL,

    target_form_id INTEGER,
    target_lang TEXT NOT NULL,
    target_term TEXT NOT NULL,

    relationship TEXT NOT NULL CHECK (relationship IN (
        'derived_from', 'inherited_from', 'borrowed_from', 'learned_borrowing_from',
        'calque_of', 'cognate_of', 'doublet_of',
        'has_root', 'has_prefix', 'has_suffix', 'has_infix', 'has_affix',
        'compound_of', 'blend_of', 'back_formation_from',
        'semantic_shift_from', 'phonetic_change_from',
        'etymologically_related_to'
    )),

    position INTEGER DEFAULT 0,
    confidence REAL DEFAULT 0.8,
    source TEXT DEFAULT 'etymology_db',

    FOREIGN KEY (source_form_id) REFERENCES surface_forms(id),
    FOREIGN KEY (target_form_id) REFERENCES surface_forms(id),
    UNIQUE (source_lang, source_term, target_lang, target_term, relationship)
);

-- ============================================================================
-- 7. GRAMMAR RULES
-- ============================================================================

CREATE TABLE grammar_rules (
    id INTEGER PRIMARY KEY,

    family_id INTEGER NOT NULL,

    rule_type TEXT NOT NULL CHECK (rule_type IN (
        'word_order', 'agreement', 'case', 'tense', 'aspect', 'mood', 'voice',
        'negation', 'question', 'relative', 'coordination', 'subordination',
        'morphophonology', 'morphotactics', 'prosody', 'orthography'
    )),
    rule_name TEXT NOT NULL,

    abstract_form TEXT,
    concrete_form TEXT,
    gbnf_pattern TEXT,
    regex_pattern TEXT,

    formal_weight REAL DEFAULT 1.0,
    nlp_weight REAL DEFAULT 0.8,

    bias_when_violated REAL DEFAULT -2.0,
    bias_when_satisfied REAL DEFAULT 0.5,

    inherited_from_id INTEGER,
    override_level TEXT DEFAULT 'extend' CHECK (override_level IN (
        'extend', 'replace', 'disable'
    )),

    confidence REAL DEFAULT 0.5,
    source TEXT,
    verified INTEGER DEFAULT 0,

    examples TEXT,
    counter_examples TEXT,
    notes TEXT,

    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT,

    FOREIGN KEY (family_id) REFERENCES language_families(id),
    FOREIGN KEY (inherited_from_id) REFERENCES grammar_rules(id),
    UNIQUE (family_id, rule_type, rule_name)
);

-- ============================================================================
-- 8. GRAMMAR EXCEPTIONS
-- ============================================================================

CREATE TABLE grammar_exceptions (
    id INTEGER PRIMARY KEY,

    rule_id INTEGER NOT NULL,
    family_id INTEGER NOT NULL,

    exception_type TEXT NOT NULL CHECK (exception_type IN (
        'lexical', 'phonological', 'semantic', 'register', 'historical', 'irregular'
    )),

    trigger_pattern TEXT NOT NULL,
    affected_morphemes TEXT,
    affected_surface_forms TEXT,

    replacement_pattern TEXT,
    replacement_rule TEXT,

    confidence REAL DEFAULT 0.7,
    notes TEXT,

    FOREIGN KEY (rule_id) REFERENCES grammar_rules(id),
    FOREIGN KEY (family_id) REFERENCES language_families(id)
);

-- ============================================================================
-- 9. DATA SOURCES
-- ============================================================================

CREATE TABLE data_sources (
    id INTEGER PRIMARY KEY,

    name TEXT NOT NULL UNIQUE,
    source_type TEXT NOT NULL CHECK (source_type IN (
        'formal_grammar', 'corpus', 'lexicon', 'nlp_tool', 'human', 'inferred'
    )),

    base_confidence REAL NOT NULL,

    url TEXT,
    version TEXT,
    license TEXT,
    citation TEXT,

    last_import TEXT,
    record_count INTEGER,

    description TEXT
);

-- ============================================================================
-- 10. PROVENANCE TRACKING
-- ============================================================================

CREATE TABLE provenance (
    id INTEGER PRIMARY KEY,

    table_name TEXT NOT NULL,
    row_id INTEGER NOT NULL,

    source_id INTEGER NOT NULL,
    source_record_id TEXT,

    confidence REAL NOT NULL,
    imported_at TEXT DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (source_id) REFERENCES data_sources(id),
    UNIQUE (table_name, row_id, source_id)
);

-- ============================================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================================

-- Language hierarchy
CREATE INDEX idx_lang_parent ON language_families(parent_id);
CREATE INDEX idx_lang_level ON language_families(level);
CREATE INDEX idx_lang_iso3 ON language_families(iso_639_3);
CREATE INDEX idx_lang_iso1 ON language_families(iso_639_1);

-- Morpheme metadata
CREATE INDEX idx_meta_category ON morpheme_metadata(category_id);

-- Surface forms (CRITICAL)
CREATE INDEX idx_sf_lookup ON surface_forms(language_id, surface_form);
CREATE INDEX idx_sf_lookup_pos ON surface_forms(language_id, surface_form, pos_tag);
CREATE INDEX idx_sf_morpheme ON surface_forms(morpheme_id);
CREATE INDEX idx_sf_type ON surface_forms(morpheme_type);
CREATE INDEX idx_sf_normalized ON surface_forms(language_id, normalized_form);

-- Etymology
CREATE INDEX idx_etym_source ON etymology_links(source_lang, source_term);
CREATE INDEX idx_etym_target ON etymology_links(target_lang, target_term);
CREATE INDEX idx_etym_rel ON etymology_links(relationship);

-- Grammar
CREATE INDEX idx_grammar_family ON grammar_rules(family_id);
CREATE INDEX idx_grammar_type ON grammar_rules(rule_type);

-- Provenance
CREATE INDEX idx_prov_table_row ON provenance(table_name, row_id);

-- ============================================================================
-- SEED DATA: Sources
-- ============================================================================

INSERT INTO data_sources (name, source_type, base_confidence, description, url) VALUES
    ('gf', 'formal_grammar', 0.95, 'Grammatical Framework', 'https://www.grammaticalframework.org/'),
    ('ud', 'corpus', 0.85, 'Universal Dependencies', 'https://universaldependencies.org/'),
    ('wals', 'corpus', 0.70, 'World Atlas of Language Structures', 'https://wals.info/'),
    ('wikidata', 'lexicon', 0.80, 'Wikidata Lexemes', 'https://www.wikidata.org/'),
    ('mmoon_hebrew', 'lexicon', 0.90, 'MMoOn Hebrew', 'https://github.com/MMoOn-Project/OpenHebrew'),
    ('morpholex_en', 'lexicon', 0.85, 'MorphoLex-en', 'https://github.com/hugomailhot/MorphoLex-en'),
    ('etymology_db', 'lexicon', 0.80, 'Wiktionary etymology', NULL),
    ('glottolog', 'lexicon', 0.95, 'Glottolog', 'https://glottolog.org/'),
    ('manual', 'human', 0.90, 'Manual curation', NULL),
    ('inferred', 'inferred', 0.40, 'Inferred patterns', NULL);

-- ============================================================================
-- SEED DATA: Categories
-- ============================================================================

INSERT INTO morpheme_categories (name, description, sort_order) VALUES
    ('action', 'Verbs and actions', 10),
    ('object', 'Concrete nouns', 20),
    ('modifier', 'Adjectives and modifiers', 30),
    ('state', 'States and conditions', 40),
    ('quantity', 'Numbers and amounts', 50),
    ('spatial', 'Location and direction', 60),
    ('temporal', 'Time and sequence', 70),
    ('relation', 'Relationships', 80),
    ('agent', 'Roles', 90),
    ('perception', 'Senses', 100),
    ('mental', 'Cognition', 110),
    ('element', 'Natural elements', 120),
    ('negation', 'Negation/opposition', 130),
    ('abstract', 'Abstract concepts', 140),
    ('grammatical', 'Grammatical function', 150);
